version: '3'
services:
  www:
    environment:
      - WWW_ROOT
      - WWW_DOCROOT
      - WWW_PORT
    image: nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ${WWW_ROOT}:/var/www/html
      - ./config/settings.php:/var/www/html${WWW_DOCROOT}sites/default/settings.php
      - ./config/settings.local.php:/var/www/html${WWW_DOCROOT}sites/default/settings.local.php
      - ./lib/drush:/usr/local/bin/drush
    ports:
      - "${WWW_PORT}:80"
    links:
      - php
  db:
    environment:
      - DB_PORT
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    image: mariadb
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ./config/dbs:/docker-entrypoint-initdb.d
      - ./log:/var/log
      - ./config/mariadb.conf.d:/etc/mysql/conf.d
      - ./lib/tuning-primer.sh:/usr/local/bin/tuning-primer.sh
  php:
    environment:
      - WWW_ROOT
      - WWW_DOCROOT
      - DNS_SERVER
    image: aloyr/php:7.1-alpine37
    expose:
      - "9000"
    volumes:
      - ${WWW_ROOT}:/var/www/html
      - ./config/settings.php:/var/www/html${WWW_DOCROOT}sites/default/settings.php
      - ./config/settings.local.php:/var/www/html${WWW_DOCROOT}sites/default/settings.local.php
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./config/php/d4dd.ini:/etc/php7/conf.d/d4dd.ini
      - ./lib/drush:/usr/local/bin/drush
    links:
      - db
      - mailcatcher
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis.conf
    command: ['redis-server', '/etc/redis.conf']
  dns:
    image: aloyr/devdns
    environment:
      - HOSTMACHINE_IP
    ports:
      - "${HOSTMACHINE_IP}:53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mailcatcher:
    image: schickling/mailcatcher
    deploy:
      replicas: 1
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  mariadb:
    labels:
      - "persistent" 
