version: '3'
services:
  www:
    environment:
      - WWW_ROOT
      - WWW_PORT
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ${WWW_ROOT}:/var/www/html
      - ./settings.php:/var/www/html/sites/default/settings.php
    ports:
      - "${WWW_PORT}:80"
    links:
      - php
  db:
    environment:
      - DB_PORT
      - MYSQL_ROOT_PASSWORD
    image: mariadb
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb:/var/lib/mysql
  php:
    environment:
      - WWW_ROOT
    image: aloyr/php
    expose:
      - "9000"
    volumes:
      - ${WWW_ROOT}:/var/www/html
      - ./settings.php:/var/www/html/sites/default/settings.php
    links:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  mariadb:
