version: '3'
services:
  www:
    volumes:
      - ##PROJECTROOT##:/var/www/##SITENAME##
      - ./sites/##SITENAME##/##SITENAME##.conf:/etc/nginx/conf.d/##SITENAME##.conf
      - ./sites/##SITENAME##/settings.d4dd.php:/var/www/##SITENAME####DOCROOT##/sites/default/settings.d4dd.php
  php:
    volumes:
      - ##PROJECTROOT##:/var/www/##SITENAME##
      - ./sites/##SITENAME##/settings.d4dd.php:/var/www/##SITENAME####DOCROOT##/sites/default/settings.d4dd.php
  db:
    volumes:
      - ./sites/##SITENAME##/db.sql.gz:/docker-entrypoint-initdb.d/##SITENAME##.sql.gz


